# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be64e9c756c59fb2f39e97b0ecd4585cf0d081d1dadfc30d241e5f309f173cf8d20666da3a3ef520d30792ef4d85d0b79408209e1899f745a513e2f8a585bdd2

test:
  secret_key_base: 7a6eadce358172f38e767bc659b9e76e05e381765a806570f4f29e5cb3b825c797d0eeb43cf23b6e431301c4457129a4c25d44fca9e32bb2269445a21ab42274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
